"use client";
import AdminLayout from "@/components/admin/AdminLayout";
import { useEffect,useState } from "react";
type Stat={value:string;label:string};type Value={title:string;description:string;icon:string};
const icons=["BookOpen","Heart","Lightbulb","Shield"];
export default function AdminAbout(){const [data,setData]=useState<any>(null);const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");const load=async()=>{const r=await fetch("/api/about",{cache:"no-store"});if(r.ok)setData(await r.json())};useEffect(()=>{void load()},[]);
const save=async()=>{if(!data)return;setBusy(true);setMessage("");try{const r=await fetch("/api/about",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});const d=await r.json();if(!r.ok)throw new Error(d.error||"ذخیره ناموفق بود.");setData(d);setMessage("تغییرات با موفقیت ذخیره شد.")}catch(e){setMessage(e instanceof Error?e.message:"خطا")}finally{setBusy(false)}};
const set=(key:string,value:any)=>setData({...data,[key]:value});
if(!data)return <AdminLayout><div className="p-7 text-sm">در حال دریافت اطلاعات...</div></AdminLayout>;
return <AdminLayout><div className="mx-auto max-w-5xl p-5 sm:p-7"><div className="mb-6"><h1 className="text-xl font-bold text-[#194342]">تنظیمات درباره مدرسه</h1><p className="mt-1 text-xs text-[#667085]">متن‌ها، آمار و ارزش‌های صفحه درباره مدرسه را مدیریت کنید.</p></div><div className="space-y-5">{[["heroBadge","برچسب بالای صفحه"],["heroTitle","عنوان اصلی"],["heroDescription","توضیح کوتاه"],["introEyebrow","برچسب معرفی"],["introTitle","عنوان معرفی"],["communityTitle","عنوان بخش جامعه"],["communityDescription","توضیح بخش جامعه"]].map(([k,l])=><label key={k} className="block text-xs font-medium">{l}<input value={data[k]} onChange={e=>set(k,e.target.value)} className="mt-1.5 w-full rounded-lg border px-3 py-2.5 text-sm"/></label>)}<label className="block text-xs font-medium">متن معرفی<textarea value={data.introContent} onChange={e=>set("introContent",e.target.value)} rows={8} className="mt-1.5 w-full rounded-lg border px-3 py-2.5 text-sm leading-7"/></label><section><h2 className="mb-3 text-sm font-bold">آمار</h2><div className="grid gap-3 sm:grid-cols-2">{(data.stats as Stat[]).map((x,i)=><div key={i} className="grid grid-cols-2 gap-2"><input value={x.value} onChange={e=>{const a=[...data.stats];a[i]={...a[i],value:e.target.value};set("stats",a)}} placeholder="مقدار" className="rounded-lg border px-3 py-2 text-sm"/><input value={x.label} onChange={e=>{const a=[...data.stats];a[i]={...a[i],label:e.target.value};set("stats",a)}} placeholder="عنوان" className="rounded-lg border px-3 py-2 text-sm"/></div>)}</div></section><section><h2 className="mb-3 text-sm font-bold">ارزش‌های مدرسه</h2><div className="space-y-3">{(data.values as Value[]).map((x,i)=><div key={i} className="grid gap-2 rounded-xl border p-3 sm:grid-cols-[1fr_1fr_120px]"><input value={x.title} onChange={e=>{const a=[...data.values];a[i]={...a[i],title:e.target.value};set("values",a)}} placeholder="عنوان" className="rounded-lg border px-3 py-2 text-sm"/><input value={x.description} onChange={e=>{const a=[...data.values];a[i]={...a[i],description:e.target.value};set("values",a)}} placeholder="توضیحات" className="rounded-lg border px-3 py-2 text-sm"/><select value={x.icon} onChange={e=>{const a=[...data.values];a[i]={...a[i],icon:e.target.value};set("values",a)}} className="rounded-lg border bg-white px-3 py-2 text-sm">{icons.map(i=><option key={i}>{i}</option>)}</select></div>)}</div></section></div>{message&&<p className="mt-4 text-sm text-[#194342]">{message}</p>}<button onClick={()=>void save()} disabled={busy} className="mt-5 rounded-lg bg-[#194342] px-5 py-2.5 text-xs font-semibold text-white">{busy?"در حال ذخیره...":"ذخیره تغییرات"}</button></div></AdminLayout>}
